# Remove Gold Drops from Mobs liks Piglins? (default: true)
removeGoldDrop: true
# Should the plugin check for updated? (default: true)
updateCheck: true
# Valid language are:
# German: de_DE
# English: en_US
language: "en_US"
# Do you want to restrict bank commands to bank plots (requires Towny)
restrictToBankPlot: false
